### ISSUE TITLE
[Bug] Recipe `hpc_large_scale` has a deprecated lambda function runtime 

### ISSUE THREAD

**Issue by paragao** [aws-samples/aws-hpc-recipes#22]
As of January 25th 2024, the Python 3.7 lambda function runtime has been deprecated by AWS. It is no longer maintained and functions cannot be created using it. 

The `hpc_large_scale` recipe uses a custom resource based on a lambda function and the runtime configure is Python 3.7. The stack fails to deploy with the message that runtime chosen for the custom resource is invalid. Changing this parameter to Python 3.9 fixes the problem and does not introduce any incompatibility. 

*How to reproduce*
1. Try to deploy the hpc_large_scale recipe 
2. The CloudFormation stack will fail deployment with the message that the runtime is deprecated.

*Expected behaviour* 
Successfully deploy the stack

**Comment by sjm446** [comment]
I popped in a PR to fix this.
