### ISSUE TITLE
res-demo-stack.yaml deployment fails due to Node v14 Lambda runtime dependency

### ISSUE THREAD

**Issue by crabba** [aws-samples/aws-hpc-recipes#23]
`recipes/res/res_demo_env/assets/res-demo-stack.yaml` [line 135](https://github.com/aws-samples/aws-hpc-recipes/blob/8f3ebf69d0ad78450ba5d8337a520158884597ee/recipes/res/res_demo_env/assets/res-demo-stack.yaml#L135C20-L135C142) includes https://research-engineering-studio-us-east-1.s3.amazonaws.com/releases/2024.01/ResearchAndEngineeringStudio.template.json which on line 3500 in the definition of Lambda function `AWSCDKCfnUtilsProviderCustomResourceProviderHandlerCF82AA57` includes `"Runtime": "nodejs14.x"`.  NodeJS v14 is [deprecated as a Lambda runtime](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) and this causes this stack deployment to fail.

**Comment by mwvaughn** [comment]
This is fixed in a recent release.
