### ISSUE TITLE
pcluster/slurm_accounting receipe fails due to S3 bucket permissions

### ISSUE THREAD

**Issue by neilmunday** [aws-samples/aws-hpc-recipes#26]
The [pcluster/slurm_accounting](https://github.com/aws-samples/aws-hpc-recipes/tree/main/recipes/pcluster/slurm_accounting) recipe relies upon the ability to access the CloudFormation template provided at:

```
https://aws-hpc-recipes.s3.${AWS::Region}.${AWS::URLSuffix}/${Version}/recipes/db/slurm_accounting_db/assets/serverless-database.yaml
```

When deploying the [recipes/pcluster/slurm_accounting/assets/launch.yaml](https://github.com/aws-samples/aws-hpc-recipes/blob/main/recipes/pcluster/slurm_accounting/assets/launch.yaml), the stack fails due to being unable to access this S3 bucket.

**Comment by neilmunday** [comment]
Regions tried:

* us-east-1
* eu-west-2

**Comment by mwvaughn** [comment]
This is being fixed in today's release.

**Comment by neilmunday** [comment]
Access still denied
